<%@ Page Title="" Async="true" Language="C#" MasterPageFile="~/MainMasterPage.Master" AutoEventWireup="true" CodeBehind="Contacts.aspx.cs" Inherits="DiaryEntityFramework.Views.Contacts" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Names="Dubai" Font-Size="22px" Text="Inserir novo contato"></asp:Label>
    <br />
    <asp:Label ID="Label3" runat="server" Font-Names="Calibri" Font-Size="16px" Text="Nome"></asp:Label>
    <br />
    <asp:TextBox ID="txbName" runat="server" Width="250px"></asp:TextBox>
    <br />
    <br />
    <asp:Label ID="Label4" runat="server" Font-Names="Calibri" Font-Size="16px" Text="Email"></asp:Label>
    <br />
    <asp:TextBox ID="txbEmail" runat="server" Width="250px"></asp:TextBox>
<asp:Button ID="btnInsert" runat="server" Font-Names="Segoe UI" Font-Size="16px" OnClick="BtnInsert_ClickAsync" style="margin-left: 28px" Text="Inserir" BackColor="#33CC33" BorderColor="Black" BorderStyle="Solid" Font-Bold="True" ForeColor="White" />
    <br />
    <br />
    <asp:Label ID="Label5" runat="server" Font-Names="Calibri" Font-Size="16px" Text="Telefone"></asp:Label>
    <br />
    <asp:TextBox ID="txbPhone" runat="server" Width="250px"></asp:TextBox>
    <br />
    <br />
    <br />
    <br />
    <asp:Label ID="Label6" runat="server" Font-Bold="True" Font-Names="Segoe UI" Font-Size="22px" Text="Lista de Contatos"></asp:Label>
    <br />
    <asp:GridView ID="GridContacts" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" 
        ItemType="DiaryEntityFramework.Models.Contact" DataKeyNames="Id" AutoGenerateColumns="False" 
        SelectMethod="GridContacts_GetDataAsync" UpdateMethod="GridContacts_UpdateItemAsync" DeleteMethod="GridContacts_DeleteItemAsync" 
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowPaging="false">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />

        <Columns>
            <asp:DynamicField HeaderText="Identicação" DataField="Id" />
            <asp:DynamicField HeaderText="Nome" DataField="Name" />
            <asp:DynamicField HeaderText="Email" DataField="Email" />
            <asp:DynamicField HeaderText="Telefone" DataField="Phone" />
        </Columns>
    </asp:GridView>
    <br />
</asp:Content>
